package com.example.pokemon;

public class data {
    public static String[][] pokemonAll() {
        String[][] allpokemon = {
                {"722", "1", "Rowlet", "モクロー", "木木梟", "grass", "flying", "30", "1.5", "https://rerollcdn.com/ARCEUS/Pokemon/Rowlet.png", "https://rerollcdn.com/ARCEUS/Pokemon/Rowlet_s.png"},
{"723", "2", "Dartrix", "フクスロー", "投羽梟", "grass", "flying", "70", "16", "https://rerollcdn.com/ARCEUS/Pokemon/Dartrix.png", "https://rerollcdn.com/ARCEUS/Pokemon/Dartrix_s.png"},
{"724", "3", "Decidueye", "ジュナイパー", "狙射樹梟", "grass", "ghost", "160", "36.6", "https://rerollcdn.com/ARCEUS/Pokemon/Decidueye%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Decidueye%20Hisuian_s.png"},
{"155", "4", "Cyndaquil", "ヒノアラシ", "火球鼠", "fire", "None", "50", "7.9", "https://rerollcdn.com/ARCEUS/Pokemon/Cyndaquil.png", "https://rerollcdn.com/ARCEUS/Pokemon/Cyndaquil_s.png"},
{"156", "5", "Guilava", "マグマラシ", "火岩鼠", "fire", "None", "90", "19", "https://rerollcdn.com/ARCEUS/Pokemon/Quilava.png", "https://rerollcdn.com/ARCEUS/Pokemon/Quilava_s.png"},
{"157", "6", "Typhlosion", "バクフーン", "火爆獸", "fire", "None", "170", "79.5", "https://rerollcdn.com/ARCEUS/Pokemon/Typhlosion%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Typhlosion%20Hisuian_s.png"},
{"501", "7", "Oshawott", "ミジュマル", "水水獺", "water", "None", "50", "5.9", "https://rerollcdn.com/ARCEUS/Pokemon/Oshawott.png", "https://rerollcdn.com/ARCEUS/Pokemon/Oshawott_s.png"},
{"502", "8", "Dewott", "フタチマル", "雙刃丸", "water", "None", "80", "24.5", "https://rerollcdn.com/ARCEUS/Pokemon/Dewott.png", "https://rerollcdn.com/ARCEUS/Pokemon/Dewott_s.png"},
{"503", "9", "Samurott", "ダイケンキ", "大劍鬼", "water", "None", "150", "94.6", "https://rerollcdn.com/ARCEUS/Pokemon/Samurott%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Samurott%20Hisuian_s.png"},
{"399", "10", "Bidoof", "ビッパ", "大牙狸", "normal", "None", "50", "20", "https://rerollcdn.com/ARCEUS/Pokemon/Bidoof.png", "https://rerollcdn.com/ARCEUS/Pokemon/Bidoof_s.png"},
{"400", "11", "Bibarel", "ビーダル", "大尾狸", "normal", "water", "100", "31.5", "https://rerollcdn.com/ARCEUS/Pokemon/Bibarel.png", "https://rerollcdn.com/ARCEUS/Pokemon/Bibarel_s.png"},
{"396", "12", "Starly", "ムックル", "姆克兒", "normal", "flying", "30", "2", "https://rerollcdn.com/ARCEUS/Pokemon/Starly.png", "https://rerollcdn.com/ARCEUS/Pokemon/Starly_s.png"},
{"397", "13", "Staravia", "ムクバード", "姆克鳥", "normal", "flying", "60", "15.5", "https://rerollcdn.com/ARCEUS/Pokemon/Staravia.png", "https://rerollcdn.com/ARCEUS/Pokemon/Staravia_s.png"},
{"398", "14", "Staraptor", "ムクホーク", "姆克鷹", "normal", "flying", "120", "24.9", "https://rerollcdn.com/ARCEUS/Pokemon/Staraptor.png", "https://rerollcdn.com/ARCEUS/Pokemon/Staraptor_s.png"},
{"403", "15", "Shinx", "コリンク", "小貓怪", "electric", "None", "50", "9.5", "https://rerollcdn.com/ARCEUS/Pokemon/Shinx.png", "https://rerollcdn.com/ARCEUS/Pokemon/Shinx_s.png"},
{"404", "16", "Luxio", "ルクシオ", "勒克貓", "electric", "None", "90", "30.5", "https://rerollcdn.com/ARCEUS/Pokemon/Luxio.png", "https://rerollcdn.com/ARCEUS/Pokemon/Luxio_s.png"},
{"405", "17", "Luxray", "レントラー", "倫琴貓", "electric", "None", "140", "42", "https://rerollcdn.com/ARCEUS/Pokemon/Luxray.png", "https://rerollcdn.com/ARCEUS/Pokemon/Luxray_s.png"},
{"265", "18", "Wurmple", "ケムッソ", "刺尾蟲", "bug", "None", "30", "3.6", "https://rerollcdn.com/ARCEUS/Pokemon/Wurmple.png", "https://rerollcdn.com/ARCEUS/Pokemon/Wurmple_s.png"},
{"266", "19", "Silcoon", "カラサリス", "甲殼繭", "bug", "None", "60", "10", "https://rerollcdn.com/ARCEUS/Pokemon/Silcoon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Silcoon_s.png"},
{"267", "20", "Beautifly", "アゲハント", "狩獵鳳蝶", "bug", "flying", "100", "28.4", "https://rerollcdn.com/ARCEUS/Pokemon/Beautifly.png", "https://rerollcdn.com/ARCEUS/Pokemon/Beautifly_s.png"},
{"268", "21", "Cascoon", "マユルド", "盾甲繭", "bug", "None", "70", "11.5", "https://rerollcdn.com/ARCEUS/Pokemon/Cascoon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Cascoon_s.png"},
{"269", "22", "Dustox", "ドクケイル", "毒粉蛾", "bug", "poison", "120", "31.6", "https://rerollcdn.com/ARCEUS/Pokemon/Dustox.png", "https://rerollcdn.com/ARCEUS/Pokemon/Dustox_s.png"},
{"77", "23", "Ponyta", "ポニータ", "小火馬", "fire", "None", "100", "30", "https://rerollcdn.com/ARCEUS/Pokemon/Ponyta.png", "https://rerollcdn.com/ARCEUS/Pokemon/Ponyta_s.png"},
{"78", "24", "Rapidash", "ギャロップ", "烈焰馬", "fire", "None", "170", "95", "https://rerollcdn.com/ARCEUS/Pokemon/Rapidash.png", "https://rerollcdn.com/ARCEUS/Pokemon/Rapidash_s.png"},
{"133", "25", "Eevee", "イーブイ", "伊布", "normal", "None", "30", "6.5", "https://rerollcdn.com/ARCEUS/Pokemon/Eevee.png", "https://rerollcdn.com/ARCEUS/Pokemon/Eevee_s.png"},
{"134", "26", "Vaporeon", "シャワーズ", "水伊布", "water", "None", "100", "29", "https://rerollcdn.com/ARCEUS/Pokemon/Vaporeon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Vaporeon_s.png"},
{"135", "27", "Jolteon", "サンダース", "雷伊布", "electric", "None", "80", "24.5", "https://rerollcdn.com/ARCEUS/Pokemon/Jolteon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Jolteon_s.png"},
{"136", "28", "Flareon", "ブースター", "火伊布", "fire", "None", "90", "25", "https://rerollcdn.com/ARCEUS/Pokemon/Flareon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Flareon_s.png"},
{"196", "29", "Espeon", "エーフィ", "太陽伊布", "psychic", "None", "90", "26.5", "https://rerollcdn.com/ARCEUS/Pokemon/Espeon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Espeon_s.png"},
{"197", "30", "Umbreon", "ブラッキー", "月亮伊布", "dark", "None", "100", "27", "https://rerollcdn.com/ARCEUS/Pokemon/Umbreon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Umbreon_s.png"},
{"470", "31", "Leafeon", "リーフィア", "葉伊布", "grass", "None", "100", "25.5", "https://rerollcdn.com/ARCEUS/Pokemon/Leafeon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Leafeon_s.png"},
{"471", "32", "Glaceon", "グレイシア", "冰伊布", "ice", "None", "80", "25.9", "https://rerollcdn.com/ARCEUS/Pokemon/Glaceon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Glaceon_s.png"},
{"700", "33", "Sylveon", "ニンフィア", "仙子伊布", "fairy", "None", "100", "23.5", "https://rerollcdn.com/ARCEUS/Pokemon/Sylveon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Sylveon_s.png"},
{"41", "34", "Zubat", "ズバット", "超音蝠", "poison", "flying", "80", "7.5", "https://rerollcdn.com/ARCEUS/Pokemon/Zubat.png", "https://rerollcdn.com/ARCEUS/Pokemon/Zubat.png"},
{"42", "35", "Golbat", "ゴルバット", "大嘴蝠", "poison", "flying", "160", "55", "https://rerollcdn.com/ARCEUS/Pokemon/Golbat.png", "https://rerollcdn.com/ARCEUS/Pokemon/Golbat_s.png"},
{"169", "36", "Crobat", "クロバット", "叉字蝠", "poison", "flying", "180", "75", "https://rerollcdn.com/ARCEUS/Pokemon/Crobat.png", "https://rerollcdn.com/ARCEUS/Pokemon/Crobat_s.png"},
{"425", "37", "Drifloon", "フワンテ", "飄飄球", "ghost", "flying", "40", "1.2", "https://rerollcdn.com/ARCEUS/Pokemon/Drifloon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Drifloon_s.png"},
{"426", "38", "Drifblim", "フワライド", "隨風球", "ghost", "flying", "120", "15", "https://rerollcdn.com/ARCEUS/Pokemon/Drifblim.png", "https://rerollcdn.com/ARCEUS/Pokemon/Drifblim_s.png"},
{"401", "39", "Kricketot", "コロボーシ", "圓法師", "bug", "None", "30", "2.2", "https://rerollcdn.com/ARCEUS/Pokemon/Kricketot.png", "https://rerollcdn.com/ARCEUS/Pokemon/Kricketot_s.png"},
{"402", "40", "Kricketune", "コロトック", "音箱蟀", "bug", "None", "100", "25.5", "https://rerollcdn.com/ARCEUS/Pokemon/Kricketune.png", "https://rerollcdn.com/ARCEUS/Pokemon/Kricketune_s.png"},
{"418", "41", "Buizel", "ブイゼル", "泳圈鼬", "water", "None", "70", "29.5", "https://rerollcdn.com/ARCEUS/Pokemon/Buizel.png", "https://rerollcdn.com/ARCEUS/Pokemon/Buizel_s.png"},
{"419", "42", "Floatzel", "フローゼル", "浮潛鼬", "water", "None", "110", "33.5", "https://rerollcdn.com/ARCEUS/Pokemon/Floatzel.png", "https://rerollcdn.com/ARCEUS/Pokemon/Floatzel_s.png"},
{"412", "43", "Burmy", "ミノムッチ", "結草兒", "bug", "None", "20", "3.4", "https://rerollcdn.com/ARCEUS/Pokemon/Burmy.png", "https://rerollcdn.com/ARCEUS/Pokemon/Burmy_s.png"},
{"413", "44", "Wormadam-plant", "ミノマダム", "結草貴婦", "bug", "grass", "50", "6.5", "https://rerollcdn.com/ARCEUS/Pokemon/Wormadam.png", "https://rerollcdn.com/ARCEUS/Pokemon/Wormadam_s.png"},
{"414", "45", "Mothim", "ガーメイル", "紳士蛾", "bug", "flying", "90", "23.3", "https://rerollcdn.com/ARCEUS/Pokemon/Mothim.png", "https://rerollcdn.com/ARCEUS/Pokemon/Mothim_s.png"},
{"74", "46", "Geodude", "イシツブテ", "小拳石", "rock", "ground", "40", "20", "https://rerollcdn.com/ARCEUS/Pokemon/Geodude.png", "https://rerollcdn.com/ARCEUS/Pokemon/Geodude_s.png"},
{"75", "47", "Graveler", "ゴローン", "隆隆石", "rock", "ground", "100", "105", "https://rerollcdn.com/ARCEUS/Pokemon/Graveler.png", "https://rerollcdn.com/ARCEUS/Pokemon/Graveler_s.png"},
{"76", "48", "Golem", "ゴローニャ", "隆隆岩", "rock", "ground", "140", "300", "https://rerollcdn.com/ARCEUS/Pokemon/Golem.png", "https://rerollcdn.com/ARCEUS/Pokemon/Golem_s.png"},
{"234", "49", "Stantler", "オドシシ", "驚角鹿", "normal", "None", "140", "71.2", "https://rerollcdn.com/ARCEUS/Pokemon/Stantler.png", "https://rerollcdn.com/ARCEUS/Pokemon/Stantler_s.png"},
{"899", "50", "Wyrdeer", "アヤシシ", "詭角鹿", "normal", "psychic", "180", "95.1", "https://rerollcdn.com/ARCEUS/Pokemon/Wyrdeer.png", "https://rerollcdn.com/ARCEUS/Pokemon/Wyrdeer_s.png"},
{"446", "51", "Munchlax", "ゴンベ", "小卡比獸", "normal", "None", "60", "105", "https://rerollcdn.com/ARCEUS/Pokemon/Munchlax.png", "https://rerollcdn.com/ARCEUS/Pokemon/Munchlax_s.png"},
{"143", "52", "Snorlax", "カビゴン", "卡比獸", "normal", "None", "210", "460", "https://rerollcdn.com/ARCEUS/Pokemon/Snorlax.png", "https://rerollcdn.com/ARCEUS/Pokemon/Snorlax_s.png"},
{"46", "53", "Paras", "パラス", "派拉斯", "bug", "grass", "30", "5.4", "https://rerollcdn.com/ARCEUS/Pokemon/Paras.png", "https://rerollcdn.com/ARCEUS/Pokemon/Paras_s.png"},
{"47", "54", "Parasect", "パラセクト", "派拉斯特", "bug", "grass", "100", "29.5", "https://rerollcdn.com/ARCEUS/Pokemon/Parasect.png", "https://rerollcdn.com/ARCEUS/Pokemon/Parasect_s.png"},
{"172", "55", "Pichu", "ピチュー", "皮丘", "electric", "None", "30", "2", "https://rerollcdn.com/ARCEUS/Pokemon/Pichu.png", "https://rerollcdn.com/ARCEUS/Pokemon/Pichu_s.png"},
{"25", "56", "Pikachu", "ピカチュウ", "皮卡丘", "electric", "None", "40", "6", "https://rerollcdn.com/ARCEUS/Pokemon/Pikachu.png", "https://rerollcdn.com/ARCEUS/Pokemon/Pikachu_s.png"},
{"26", "57", "Raichu", "ライチュウ", "雷丘", "electric", "None", "80", "30", "https://rerollcdn.com/ARCEUS/Pokemon/Raichu.png", "https://rerollcdn.com/ARCEUS/Pokemon/Raichu_s.png"},
{"63", "58", "Abra", "ケーシィ", "凱西", "psychic", "None", "90", "19.5", "https://rerollcdn.com/ARCEUS/Pokemon/Abra.png", "https://rerollcdn.com/ARCEUS/Pokemon/Abra_s.png"},
{"64", "59", "Kadabra", "ユンゲラー", "勇基拉", "psychic", "None", "130", "56.5", "https://rerollcdn.com/ARCEUS/Pokemon/Kadabra.png", "https://rerollcdn.com/ARCEUS/Pokemon/Kadabra_s.png"},
{"65", "60", "Alakazam", "フーディン", "胡地", "psychic", "None", "150", "48", "https://rerollcdn.com/ARCEUS/Pokemon/Alakazam.png", "https://rerollcdn.com/ARCEUS/Pokemon/Alakazam_s.png"},
{"390", "61", "Chimchar", "ヒコザル", "小火焰猴", "fire", "None", "50", "6.2", "https://rerollcdn.com/ARCEUS/Pokemon/Chimchar.png", "https://rerollcdn.com/ARCEUS/Pokemon/Chimchar_s.png"},
{"391", "62", "Monferno", "モウカザル", "猛火猴", "fire", "fighting", "90", "22", "https://rerollcdn.com/ARCEUS/Pokemon/Monferno.png", "https://rerollcdn.com/ARCEUS/Pokemon/Monferno_s.png"},
{"392", "63", "Infernape", "ゴウカザル", "烈焰猴", "fire", "fighting", "120", "55", "https://rerollcdn.com/ARCEUS/Pokemon/Infernape.png", "https://rerollcdn.com/ARCEUS/Pokemon/Infernape_s.png"},
{"427", "64", "Buneary", "ミミロル", "捲捲耳", "normal", "None", "40", "5.5", "https://rerollcdn.com/ARCEUS/Pokemon/Buneary.png", "https://rerollcdn.com/ARCEUS/Pokemon/Buneary_s.png"},
{"428", "65", "Lopunny", "ミミロップ", "長耳兔", "normal", "None", "120", "33.3", "https://rerollcdn.com/ARCEUS/Pokemon/Lopunny.png", "https://rerollcdn.com/ARCEUS/Pokemon/Lopunny_s.png"},
{"420", "66", "Cherubi", "チェリンボ", "櫻花寶", "grass", "None", "40", "3.3", "https://rerollcdn.com/ARCEUS/Pokemon/Cherubi.png", "https://rerollcdn.com/ARCEUS/Pokemon/Cherubi_s.png"},
{"421", "67", "Cherrim", "チェリム", "櫻花兒", "grass", "None", "50", "9.3", "https://rerollcdn.com/ARCEUS/Pokemon/Cherrim.png", "https://rerollcdn.com/ARCEUS/Pokemon/Cherrim_s.png"},
{"54", "68", "Psyduck", "コダック", "可達鴨", "water", "None", "80", "19.6", "https://rerollcdn.com/ARCEUS/Pokemon/Psyduck.png", "https://rerollcdn.com/ARCEUS/Pokemon/Psyduck_s.png"},
{"55", "69", "Golduck", "ゴルダック", "哥達鴨", "water", "None", "170", "76.6", "https://rerollcdn.com/ARCEUS/Pokemon/Golduck.png", "https://rerollcdn.com/ARCEUS/Pokemon/Golduck_s.png"},
{"415", "70", "Combee", "ミツハニー", "三蜜蜂", "bug", "flying", "30", "5.5", "https://rerollcdn.com/ARCEUS/Pokemon/Combee.png", "https://rerollcdn.com/ARCEUS/Pokemon/Combee_s.png"},
{"416", "71", "Vespiquen", "ビークイン", "蜂女王", "bug", "flying", "120", "38.5", "https://rerollcdn.com/ARCEUS/Pokemon/Vespiquen.png", "https://rerollcdn.com/ARCEUS/Pokemon/Vespiquen_s.png"},
{"123", "72", "Scyther", "ストライク", "飛天螳螂", "bug", "flying", "150", "56", "https://rerollcdn.com/ARCEUS/Pokemon/Scyther.png", "https://rerollcdn.com/ARCEUS/Pokemon/Scyther_s.png"},
{"212", "73", "Scizor", "ハッサム", "巨鉗螳螂", "bug", "steel", "180", "118", "https://rerollcdn.com/ARCEUS/Pokemon/Kleavor.png", "https://rerollcdn.com/ARCEUS/Pokemon/Kleavor_s.png"},
{"900", "74", "Kleavor", "バサギリ", "劈斧螳螂", "bug", "rock", "180", "89", "https://rerollcdn.com/ARCEUS/Pokemon/Scizor.png", "https://rerollcdn.com/ARCEUS/Pokemon/Scizor_s.png"},
{"214", "75", "Heracross", "ヘラクロス", "赫拉克羅斯", "bug", "fighting", "150", "54", "https://rerollcdn.com/ARCEUS/Pokemon/Heracross.png", "https://rerollcdn.com/ARCEUS/Pokemon/Heracross_s.png"},
{"439", "76", "Mime-jr", "マネネ", "魔尼尼", "psychic", "fairy", "60", "13", "https://rerollcdn.com/ARCEUS/Pokemon/Mime%20Jr..png", "https://rerollcdn.com/ARCEUS/Pokemon/Mime%20Jr._s.png"},
{"122", "77", "Mr-mime", "バリヤード", "魔牆人偶", "psychic", "fairy", "130", "54.5", "https://rerollcdn.com/ARCEUS/Pokemon/Mr.%20Mime.png", "https://rerollcdn.com/ARCEUS/Pokemon/Mr.%20Mime_s.png"},
{"190", "78", "Aipom", "エイパム", "長尾怪手", "normal", "None", "80", "11.5", "https://rerollcdn.com/ARCEUS/Pokemon/Aipom.png", "https://rerollcdn.com/ARCEUS/Pokemon/Aipom_s.png"},
{"424", "79", "Ambipom", "エテボース", "雙尾怪手", "normal", "None", "120", "20.3", "https://rerollcdn.com/ARCEUS/Pokemon/Ambipom.png", "https://rerollcdn.com/ARCEUS/Pokemon/Ambipom_s.png"},
{"129", "80", "Magikarp", "コイキング", "鯉魚王", "water", "None", "90", "10", "https://rerollcdn.com/ARCEUS/Pokemon/Magikarp.png", "https://rerollcdn.com/ARCEUS/Pokemon/Magikarp_s.png"},
{"130", "81", "Gyarados", "ギャラドス", "暴鯉龍", "water", "flying", "650", "235", "https://rerollcdn.com/ARCEUS/Pokemon/Gyarados.png", "https://rerollcdn.com/ARCEUS/Pokemon/Gyarados_s.png"},
{"422", "82", "Shellos", "カラナクシ", "無殼海兔", "water", "None", "30", "6.3", "https://rerollcdn.com/ARCEUS/Pokemon/Shellos.png", "https://rerollcdn.com/ARCEUS/Pokemon/Shellos_s.png"},
{"423", "83", "Gastrodon", "トリトドン", "海兔獸", "water", "ground", "90", "29.9", "https://rerollcdn.com/ARCEUS/Pokemon/Gastrodon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Gastrodon_s.png"},
{"211", "84", "Gwilfish", "ハリーセン", "千針魚", "water", "poison", "50", "3.9", "https://rerollcdn.com/ARCEUS/Pokemon/Qwilfish%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Qwilfish%20Hisuian_s.png"},
{"904", "85", "Overqwil", "ハリーマン", "萬針魚", "dark", "poison", "250", "60.5", "https://rerollcdn.com/ARCEUS/Pokemon/Overqwil.png", "https://rerollcdn.com/ARCEUS/Pokemon/Overqwil_s.png"},
{"440", "86", "Happiny", "ピンプク", "小福蛋", "normal", "None", "60", "24.4", "https://rerollcdn.com/ARCEUS/Pokemon/Happiny.png", "https://rerollcdn.com/ARCEUS/Pokemon/Happiny_s.png"},
{"113", "87", "Chansey", "ラッキー", "吉利蛋", "normal", "None", "110", "34.6", "https://rerollcdn.com/ARCEUS/Pokemon/Chansey.png", "https://rerollcdn.com/ARCEUS/Pokemon/Chansey_s.png"},
{"242", "88", "Blissey", "ハピナス", "幸福蛋", "normal", "None", "150", "46.8", "https://rerollcdn.com/ARCEUS/Pokemon/Blissey.png", "https://rerollcdn.com/ARCEUS/Pokemon/Blissey_s.png"},
{"406", "89", "Budew", "スボミー", "含羞苞", "grass", "poison", "20", "1.2", "https://rerollcdn.com/ARCEUS/Pokemon/Budew.png", "https://rerollcdn.com/ARCEUS/Pokemon/Budew_s.png"},
{"315", "90", "Roselia", "ロゼリア", "毒薔薇", "grass", "poison", "30", "2", "https://rerollcdn.com/ARCEUS/Pokemon/Roselia.png", "https://rerollcdn.com/ARCEUS/Pokemon/Roselia_s.png"},
{"407", "91", "Roserade", "ロズレイド", "羅絲雷朵", "grass", "poison", "90", "14.5", "https://rerollcdn.com/ARCEUS/Pokemon/Roserade.png", "https://rerollcdn.com/ARCEUS/Pokemon/Roserade_s.png"},
{"455", "92", "Carnivine", "マスキッパ", "尖牙籠", "grass", "None", "140", "27", "https://rerollcdn.com/ARCEUS/Pokemon/Carnivine.png", "https://rerollcdn.com/ARCEUS/Pokemon/Carnivine_s.png"},
{"548", "93", "Petilil", "チュリネ", "百合根娃娃", "grass", "None", "50", "6.6", "https://rerollcdn.com/ARCEUS/Pokemon/Petilil.png", "https://rerollcdn.com/ARCEUS/Pokemon/Petilil_s.png"},
{"549", "94", "Lilligant", "ドレディア", "裙兒小姐", "grass", "None", "110", "16.3", "https://rerollcdn.com/ARCEUS/Pokemon/Lilligant%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Lilligant%20Hisuian_s.png"},
{"114", "95", "Tangela", "モンジャラ", "蔓藤怪", "grass", "None", "100", "35", "https://rerollcdn.com/ARCEUS/Pokemon/Tangela.png", "https://rerollcdn.com/ARCEUS/Pokemon/Tangela_s.png"},
{"465", "96", "Tangrowth", "モジャンボ", "巨蔓藤", "grass", "None", "200", "128.6", "https://rerollcdn.com/ARCEUS/Pokemon/Tangrowth.png", "https://rerollcdn.com/ARCEUS/Pokemon/Tangrowth_s.png"},
{"339", "97", "Barboach", "ドジョッチ", "泥泥鰍", "water", "ground", "40", "1.9", "https://rerollcdn.com/ARCEUS/Pokemon/Barboach.png", "https://rerollcdn.com/ARCEUS/Pokemon/Barboach_s.png"},
{"340", "98", "Whiscash", "ナマズン", "鯰魚王", "water", "ground", "90", "23.6", "https://rerollcdn.com/ARCEUS/Pokemon/Whiscash.png", "https://rerollcdn.com/ARCEUS/Pokemon/Whiscash_s.png"},
{"453", "99", "Croagunk", "グレッグル", "不良蛙", "poison", "fighting", "70", "23", "https://rerollcdn.com/ARCEUS/Pokemon/Croagunk.png", "https://rerollcdn.com/ARCEUS/Pokemon/Croagunk_s.png"},
{"454", "100", "Toxicroak", "ドクロッグ", "毒骷蛙", "poison", "fighting", "130", "44.4", "https://rerollcdn.com/ARCEUS/Pokemon/Toxicroak.png", "https://rerollcdn.com/ARCEUS/Pokemon/Toxicroak_s.png"},
{"280", "101", "Ralts", "ラルトス", "拉魯拉絲", "psychic", "fairy", "40", "6.6", "https://rerollcdn.com/ARCEUS/Pokemon/Ralts.png", "https://rerollcdn.com/ARCEUS/Pokemon/Ralts_s.png"},
{"281", "102", "Kirlia", "キルリア", "奇魯莉安", "psychic", "fairy", "80", "20.2", "https://rerollcdn.com/ARCEUS/Pokemon/Kirlia.png", "https://rerollcdn.com/ARCEUS/Pokemon/Kirlia_s.png"},
{"282", "103", "Gardevoir", "サーナイト", "沙奈朵", "psychic", "fairy", "160", "48.4", "https://rerollcdn.com/ARCEUS/Pokemon/Gardevoir.png", "https://rerollcdn.com/ARCEUS/Pokemon/Gardevoir_s.png"},
{"475", "104", "Gallade", "エルレイド", "艾路雷朵", "psychic", "fighting", "160", "52", "https://rerollcdn.com/ARCEUS/Pokemon/Gallade.png", "https://rerollcdn.com/ARCEUS/Pokemon/Gallade_s.png"},
{"193", "105", "Yanma", "ヤンヤンマ", "蜻蜻蜓", "bug", "flying", "120", "38", "https://rerollcdn.com/ARCEUS/Pokemon/Yanma.png", "https://rerollcdn.com/ARCEUS/Pokemon/Yanma_s.png"},
{"469", "106", "Yanmega", "メガヤンマ", "遠古巨蜓", "bug", "flying", "190", "51.5", "https://rerollcdn.com/ARCEUS/Pokemon/Yanmega.png", "https://rerollcdn.com/ARCEUS/Pokemon/Yanmega_s.png"},
{"449", "107", "Hippopotas", "ヒポポタス", "沙河馬", "ground", "None", "80", "49.5", "https://rerollcdn.com/ARCEUS/Pokemon/Hippopotas.png", "https://rerollcdn.com/ARCEUS/Pokemon/Hippopotas_s.png"},
{"450", "108", "Hippowdon", "カバルドン", "河馬獸", "ground", "None", "200", "300", "https://rerollcdn.com/ARCEUS/Pokemon/Hippowdon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Hippowdon_s.png"},
{"417", "109", "Pachirisu", "パチリス", "帕奇利茲", "electric", "None", "40", "3.9", "https://rerollcdn.com/ARCEUS/Pokemon/Pachirisu.png", "https://rerollcdn.com/ARCEUS/Pokemon/Pachirisu_s.png"},
{"434", "110", "Stunky", "スカンプー", "臭鼬噗", "poison", "dark", "40", "19.2", "https://rerollcdn.com/ARCEUS/Pokemon/Stunky.png", "https://rerollcdn.com/ARCEUS/Pokemon/Stunky_s.png"},
{"435", "111", "Skuntank", "スカタンク", "坦克臭鼬", "poison", "dark", "100", "38", "https://rerollcdn.com/ARCEUS/Pokemon/Skuntank.png", "https://rerollcdn.com/ARCEUS/Pokemon/Skuntank_s.png"},
{"216", "112", "Teddiursa", "ヒメグマ", "熊寶寶", "normal", "None", "60", "8.8", "https://rerollcdn.com/ARCEUS/Pokemon/Teddiursa.png", "https://rerollcdn.com/ARCEUS/Pokemon/Teddiursa_s.png"},
{"217", "113", "Ursaring", "リングマ", "圈圈熊", "normal", "None", "180", "125.8", "https://rerollcdn.com/ARCEUS/Pokemon/Ursaring.png", "https://rerollcdn.com/ARCEUS/Pokemon/Ursaring_s.png"},
{"901", "114", "Ursaluna", "ガチグマ", "月月熊", "ground", "normal", "240", "290", "https://rerollcdn.com/ARCEUS/Pokemon/Ursaluna.png", "https://rerollcdn.com/ARCEUS/Pokemon/Ursaluna_s.png"},
{"704", "115", "Goomy", "ヌメラ", "黏黏寶", "dragon", "None", "30", "2.8", "https://rerollcdn.com/ARCEUS/Pokemon/Goomy.png", "https://rerollcdn.com/ARCEUS/Pokemon/Goomy_s.png"},
{"705", "116", "Sliggoo", "ヌメイル", "黏美兒", "dragon", "None", "80", "17.5", "https://rerollcdn.com/ARCEUS/Pokemon/Sliggoo%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Sliggoo%20Hisuian_s.png"},
{"706", "117", "Goodra", "ヌメルゴン", "黏美龍", "dragon", "None", "200", "150.5", "https://rerollcdn.com/ARCEUS/Pokemon/Goodra%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Goodra%20Hisuian_s.png"},
{"95", "118", "Onix", "イワーク", "大岩蛇", "rock", "ground", "880", "210", "https://rerollcdn.com/ARCEUS/Pokemon/Onix.png", "https://rerollcdn.com/ARCEUS/Pokemon/Onix_s.png"},
{"208", "119", "Steelix", "ハガネール", "大鋼蛇", "steel", "ground", "920", "400", "https://rerollcdn.com/ARCEUS/Pokemon/Steelix.png", "https://rerollcdn.com/ARCEUS/Pokemon/Steelix_s.png"},
{"111", "120", "Rhyhorn", "サイホーン", "獨角犀牛", "ground", "rock", "100", "115", "https://rerollcdn.com/ARCEUS/Pokemon/Rhyhorn.png", "https://rerollcdn.com/ARCEUS/Pokemon/Rhyhorn_s.png"},
{"112", "121", "Rhydon", "サイドン", "鑽角犀獸", "ground", "rock", "190", "120", "https://rerollcdn.com/ARCEUS/Pokemon/Rhydon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Rhydon_s.png"},
{"464", "122", "Rhyperior", "ドサイドン", "超甲狂犀", "ground", "rock", "240", "282.8", "https://rerollcdn.com/ARCEUS/Pokemon/Rhyperior.png", "https://rerollcdn.com/ARCEUS/Pokemon/Rhyperior_s.png"},
{"438", "123", "Bonsly", "ウソハチ", "盆才怪", "rock", "None", "50", "15", "https://rerollcdn.com/ARCEUS/Pokemon/Bonsly.png", "https://rerollcdn.com/ARCEUS/Pokemon/Bonsly_s.png"},
{"185", "124", "Sudowoodo", "ウソッキー", "樹才怪", "rock", "None", "120", "38", "https://rerollcdn.com/ARCEUS/Pokemon/Sudowoodo.png", "https://rerollcdn.com/ARCEUS/Pokemon/Sudowoodo_s.png"},
{"108", "125", "Lickitung", "ベロリンガ", "大舌頭", "normal", "None", "120", "65.5", "https://rerollcdn.com/ARCEUS/Pokemon/Lickitung.png", "https://rerollcdn.com/ARCEUS/Pokemon/Lickitung_s.png"},
{"463", "126", "Lickilicky", "ベロベルト", "大舌舔", "normal", "None", "170", "140", "https://rerollcdn.com/ARCEUS/Pokemon/Lickilicky.png", "https://rerollcdn.com/ARCEUS/Pokemon/Lickilicky_s.png"},
{"175", "127", "Togepi", "トゲピー", "波克比", "fairy", "None", "30", "1.5", "https://rerollcdn.com/ARCEUS/Pokemon/Togepi.png", "https://rerollcdn.com/ARCEUS/Pokemon/Togepi_s.png"},
{"176", "128", "Togetic", "トゲチック", "波克基古", "fairy", "flying", "60", "3.2", "https://rerollcdn.com/ARCEUS/Pokemon/Togetic.png", "https://rerollcdn.com/ARCEUS/Pokemon/Togetic_s.png"},
{"468", "129", "Togekiss", "トゲキッス", "波克基斯", "fairy", "flying", "150", "38", "https://rerollcdn.com/ARCEUS/Pokemon/Togekiss.png", "https://rerollcdn.com/ARCEUS/Pokemon/Togekiss_s.png"},
{"387", "130", "Turtwig", "ナエトル", "草苗龜", "grass", "None", "40", "10.2", "https://rerollcdn.com/ARCEUS/Pokemon/Turtwig.png", "https://rerollcdn.com/ARCEUS/Pokemon/Turtwig_s.png"},
{"388", "131", "Grotle", "ハヤシガメ", "樹林龜", "grass", "None", "110", "97", "https://rerollcdn.com/ARCEUS/Pokemon/Grotle.png", "https://rerollcdn.com/ARCEUS/Pokemon/Grotle_s.png"},
{"389", "132", "Torterra", "ドダイトス", "土台龜", "grass", "ground", "220", "310", "https://rerollcdn.com/ARCEUS/Pokemon/Torterra.png", "https://rerollcdn.com/ARCEUS/Pokemon/Torterra_s.png"},
{"137", "133", "Porygon", "ポリゴン", "多邊獸", "normal", "None", "80", "36.5", "https://rerollcdn.com/ARCEUS/Pokemon/Porygon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Porygon_s.png"},
{"233", "134", "Porygon2", "ポリゴン２", "多邊獸Ⅱ", "normal", "None", "60", "32.5", "https://rerollcdn.com/ARCEUS/Pokemon/Porygon2.png", "https://rerollcdn.com/ARCEUS/Pokemon/Porygon2_s.png"},
{"474", "135", "Porygon-z", "ポリゴンＺ", "多邊獸Ｚ", "normal", "None", "90", "34", "https://rerollcdn.com/ARCEUS/Pokemon/Porygon%20Z.png", "https://rerollcdn.com/ARCEUS/Pokemon/Porygon%20Z_s.png"},
{"92", "136", "Gastly", "ゴース", "鬼斯", "ghost", "poison", "130", "0.1", "https://rerollcdn.com/ARCEUS/Pokemon/Gastly.png", "https://rerollcdn.com/ARCEUS/Pokemon/Gastly_s.png"},
{"93", "137", "Haunter", "ゴースト", "鬼斯通", "ghost", "poison", "160", "0.1", "https://rerollcdn.com/ARCEUS/Pokemon/Haunter.png", "https://rerollcdn.com/ARCEUS/Pokemon/Haunter_s.png"},
{"94", "138", "Gengar", "ゲンガー", "耿鬼", "ghost", "poison", "150", "40.5", "https://rerollcdn.com/ARCEUS/Pokemon/Gengar.png", "https://rerollcdn.com/ARCEUS/Pokemon/Gengar_s.png"},
{"442", "139", "Spiritomb", "ミカルゲ", "花岩怪", "ghost", "dark", "100", "108", "https://rerollcdn.com/ARCEUS/Pokemon/Spiritomb.png", "https://rerollcdn.com/ARCEUS/Pokemon/Spiritomb_s.png"},
{"198", "140", "Murkrow", "ヤミカラス", "黑暗鴉", "dark", "flying", "50", "2.1", "https://rerollcdn.com/ARCEUS/Pokemon/Murkrow.png", "https://rerollcdn.com/ARCEUS/Pokemon/Murkrow_s.png"},
{"430", "141", "Honchkrow", "ドンカラス", "烏鴉頭頭", "dark", "flying", "90", "27.3", "https://rerollcdn.com/ARCEUS/Pokemon/Honchkrow.png", "https://rerollcdn.com/ARCEUS/Pokemon/Honchkrow_s.png"},
{"201", "142", "Unown", "アンノーン", "未知圖騰", "psychic", "None", "50", "5", "https://rerollcdn.com/ARCEUS/Pokemon/Unown.png", "https://rerollcdn.com/ARCEUS/Pokemon/Unown_s.png"},
{"363", "143", "Spheal", "タマザラシ", "海豹球", "ice", "water", "80", "39.5", "https://rerollcdn.com/ARCEUS/Pokemon/Spheal.png", "https://rerollcdn.com/ARCEUS/Pokemon/Spheal_s.png"},
{"364", "144", "Sealeo", "トドグラー", "海魔獅", "ice", "water", "110", "87.6", "https://rerollcdn.com/ARCEUS/Pokemon/Sealeo.png", "https://rerollcdn.com/ARCEUS/Pokemon/Sealeo_s.png"},
{"365", "145", "Walrein", "トドゼルガ", "帝牙海獅", "ice", "water", "140", "150.6", "https://rerollcdn.com/ARCEUS/Pokemon/Walrein.png", "https://rerollcdn.com/ARCEUS/Pokemon/Walrein_s.png"},
{"223", "146", "Remoraid", "テッポウオ", "鐵炮魚", "water", "None", "60", "12", "https://rerollcdn.com/ARCEUS/Pokemon/Remoraid.png", "https://rerollcdn.com/ARCEUS/Pokemon/Remoraid_s.png"},
{"224", "147", "Octillery", "オクタン", "章魚桶", "water", "None", "90", "28.5", "https://rerollcdn.com/ARCEUS/Pokemon/Octillery.png", "https://rerollcdn.com/ARCEUS/Pokemon/Octillery_s.png"},
{"451", "148", "Skorupi", "スコルピ", "鉗尾蠍", "poison", "bug", "80", "12", "https://rerollcdn.com/ARCEUS/Pokemon/Skorupi.png", "https://rerollcdn.com/ARCEUS/Pokemon/Skorupi_s.png"},
{"452", "149", "Drapion", "ドラピオン", "龍王蠍", "poison", "dark", "130", "61.5", "https://rerollcdn.com/ARCEUS/Pokemon/Drapion.png", "https://rerollcdn.com/ARCEUS/Pokemon/Drapion_s.png"},
{"58", "150", "Growlithe", "ガーディ", "卡蒂狗", "fire", "None", "70", "19", "https://rerollcdn.com/ARCEUS/Pokemon/Growlithe%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Growlithe%20Hisuian_s.png"},
{"59", "151", "Arcanine", "ウインディ", "風速狗", "fire", "None", "190", "155", "https://rerollcdn.com/ARCEUS/Pokemon/Arcanine%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Arcanine%20Hisuian_s.png"},
{"431", "152", "Glameow", "ニャルマー", "魅力喵", "normal", "None", "50", "3.9", "https://rerollcdn.com/ARCEUS/Pokemon/Glameow.png", "https://rerollcdn.com/ARCEUS/Pokemon/Glameow_s.png"},
{"432", "153", "Purugly", "ブニャット", "東施喵", "normal", "None", "100", "43.8", "https://rerollcdn.com/ARCEUS/Pokemon/Purugly.png", "https://rerollcdn.com/ARCEUS/Pokemon/Purugly_s.png"},
{"66", "154", "Machop", "ワンリキー", "腕力", "fighting", "None", "80", "19.5", "https://rerollcdn.com/ARCEUS/Pokemon/Machop.png", "https://rerollcdn.com/ARCEUS/Pokemon/Machop_s.png"},
{"67", "155", "Machoke", "ゴーリキー", "豪力", "fighting", "None", "150", "70.5", "https://rerollcdn.com/ARCEUS/Pokemon/Machoke.png", "https://rerollcdn.com/ARCEUS/Pokemon/Machoke_s.png"},
{"68", "156", "Machamp", "カイリキー", "怪力", "fighting", "None", "160", "130", "https://rerollcdn.com/ARCEUS/Pokemon/Machamp.png", "https://rerollcdn.com/ARCEUS/Pokemon/Machamp_s.png"},
{"441", "157", "Chatot", "ペラップ", "聒噪鳥", "normal", "flying", "50", "1.9", "https://rerollcdn.com/ARCEUS/Pokemon/Chatot.png", "https://rerollcdn.com/ARCEUS/Pokemon/Chatot_s.png"},
{"355", "158", "Duskull", "ヨマワル", "夜巡靈", "ghost", "None", "80", "15", "https://rerollcdn.com/ARCEUS/Pokemon/Duskull.png", "https://rerollcdn.com/ARCEUS/Pokemon/Duskull_s.png"},
{"356", "159", "Dusclops", "サマヨール", "彷徨夜靈", "ghost", "None", "160", "30.6", "https://rerollcdn.com/ARCEUS/Pokemon/Dusclops.png", "https://rerollcdn.com/ARCEUS/Pokemon/Dusclops_s.png"},
{"477", "160", "Dusknoir", "ヨノワール", "黑夜魔靈", "ghost", "None", "220", "106.6", "https://rerollcdn.com/ARCEUS/Pokemon/Dusknoir.png", "https://rerollcdn.com/ARCEUS/Pokemon/Dusknoir_s.png"},
{"393", "161", "Piplup", "ポッチャマ", "波加曼", "water", "None", "40", "5.2", "https://rerollcdn.com/ARCEUS/Pokemon/Piplup.png", "https://rerollcdn.com/ARCEUS/Pokemon/Piplup_s.png"},
{"394", "162", "Prinplup", "ポッタイシ", "波皇子", "water", "None", "80", "23", "https://rerollcdn.com/ARCEUS/Pokemon/Prinplup.png", "https://rerollcdn.com/ARCEUS/Pokemon/Prinplup_s.png"},
{"395", "163", "Empoleon", "エンペルト", "帝王拿波", "water", "steel", "170", "84.5", "https://rerollcdn.com/ARCEUS/Pokemon/Empoleon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Empoleon_s.png"},
{"458", "164", "Mantyke", "タマンタ", "小球飛魚", "water", "flying", "100", "65", "https://rerollcdn.com/ARCEUS/Pokemon/Mantyke.png", "https://rerollcdn.com/ARCEUS/Pokemon/Mantyke_s.png"},
{"226", "165", "Mantine", "マンタイン", "巨翅飛魚", "water", "flying", "210", "220", "https://rerollcdn.com/ARCEUS/Pokemon/Mantine.png", "https://rerollcdn.com/ARCEUS/Pokemon/Mantine_s.png"},
{"550", "166", "Basculin-red-striped", "バスラオ", "野蠻鱸魚", "water", "None", "100", "18", "https://rerollcdn.com/ARCEUS/Pokemon/Basculin%20White%20Striped.png", "https://rerollcdn.com/ARCEUS/Pokemon/Basculin%20White%20Striped_s.png"},
{"902", "167", "Basculegion", "イダイトウ", "幽尾玄魚", "water", "ghost", "300", "110", "https://rerollcdn.com/ARCEUS/Pokemon/Basculegion%20Male.png", "https://rerollcdn.com/ARCEUS/Pokemon/Basculegion%20Male_s.png"},
{"37", "168", "Vulpix", "ロコン", "六尾", "fire", "None", "60", "9.9", "https://rerollcdn.com/ARCEUS/Pokemon/Vulpix.png", "https://rerollcdn.com/ARCEUS/Pokemon/Vulpix_s.png"},
{"38", "169", "Ninetales", "キュウコン", "九尾", "fire", "None", "110", "19.9", "https://rerollcdn.com/ARCEUS/Pokemon/Ninetales.png", "https://rerollcdn.com/ARCEUS/Pokemon/Ninetales_s.png"},
{"72", "170", "Tentacool", "メノクラゲ", "瑪瑙水母", "water", "poison", "90", "45.5", "https://rerollcdn.com/ARCEUS/Pokemon/Tentacool.png", "https://rerollcdn.com/ARCEUS/Pokemon/Tentacool_s.png"},
{"73", "171", "Tentacruel", "ドククラゲ", "毒刺水母", "water", "poison", "160", "55", "https://rerollcdn.com/ARCEUS/Pokemon/Tentacruel.png", "https://rerollcdn.com/ARCEUS/Pokemon/Tentacruel_s.png"},
{"456", "172", "Finneon", "ケイコウオ", "螢光魚", "water", "None", "40", "7", "https://rerollcdn.com/ARCEUS/Pokemon/Finneon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Finneon_s.png"},
{"457", "173", "Lumineon", "ネオラント", "霓虹魚", "water", "None", "120", "24", "https://rerollcdn.com/ARCEUS/Pokemon/Lumineon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Lumineon_s.png"},
{"240", "174", "Magby", "ブビィ", "鴨嘴寶寶", "fire", "None", "70", "21.4", "https://rerollcdn.com/ARCEUS/Pokemon/Magby.png", "https://rerollcdn.com/ARCEUS/Pokemon/Magby_s.png"},
{"126", "175", "Magmar", "ブーバー", "鴨嘴火獸", "fire", "None", "130", "44.5", "https://rerollcdn.com/ARCEUS/Pokemon/Magmar.png", "https://rerollcdn.com/ARCEUS/Pokemon/Magmar_s.png"},
{"467", "176", "Magmortar", "ブーバーン", "鴨嘴炎獸", "fire", "None", "160", "68", "https://rerollcdn.com/ARCEUS/Pokemon/Magmortar.png", "https://rerollcdn.com/ARCEUS/Pokemon/Magmortar_s.png"},
{"81", "177", "Magnemite", "コイル", "小磁怪", "electric", "steel", "30", "6", "https://rerollcdn.com/ARCEUS/Pokemon/Magnemite.png", "https://rerollcdn.com/ARCEUS/Pokemon/Magnemite_s.png"},
{"82", "178", "Magneton", "レアコイル", "三合一磁怪", "electric", "steel", "100", "60", "https://rerollcdn.com/ARCEUS/Pokemon/Magneton.png", "https://rerollcdn.com/ARCEUS/Pokemon/Magneton_s.png"},
{"462", "179", "Magnezone", "ジバコイル", "自爆磁怪", "electric", "steel", "120", "180", "https://rerollcdn.com/ARCEUS/Pokemon/Magnezone.png", "https://rerollcdn.com/ARCEUS/Pokemon/Magnezone_s.png"},
{"436", "180", "Bronzor", "ドーミラー", "銅鏡怪", "steel", "psychic", "50", "60.5", "https://rerollcdn.com/ARCEUS/Pokemon/Bronzor.png", "https://rerollcdn.com/ARCEUS/Pokemon/Bronzor_s.png"},
{"437", "181", "Bronzong", "ドータクン", "青銅鐘", "steel", "psychic", "130", "187", "https://rerollcdn.com/ARCEUS/Pokemon/Bronzong.png", "https://rerollcdn.com/ARCEUS/Pokemon/Bronzong_s.png"},
{"239", "182", "Elekid", "エレキッド", "電擊怪", "electric", "None", "60", "23.5", "https://rerollcdn.com/ARCEUS/Pokemon/Elekid.png", "https://rerollcdn.com/ARCEUS/Pokemon/Elekid_s.png"},
{"125", "183", "Electabuzz", "エレブー", "電擊獸", "electric", "None", "110", "30", "https://rerollcdn.com/ARCEUS/Pokemon/Electabuzz.png", "https://rerollcdn.com/ARCEUS/Pokemon/Electabuzz_s.png"},
{"466", "184", "Electivire", "エレキブル", "電擊魔獸", "electric", "None", "180", "138.6", "https://rerollcdn.com/ARCEUS/Pokemon/Electivire.png", "https://rerollcdn.com/ARCEUS/Pokemon/Electivire_s.png"},
{"207", "185", "Gligar", "グライガー", "天蠍", "ground", "flying", "110", "64.8", "https://rerollcdn.com/ARCEUS/Pokemon/Gligar.png", "https://rerollcdn.com/ARCEUS/Pokemon/Gligar_s.png"},
{"472", "186", "Gliscor", "グライオン", "天蠍王", "ground", "flying", "200", "42.5", "https://rerollcdn.com/ARCEUS/Pokemon/Gliscor.png", "https://rerollcdn.com/ARCEUS/Pokemon/Gliscor_s.png"},
{"443", "187", "Gible", "フカマル", "圓陸鯊", "dragon", "ground", "70", "20.5", "https://rerollcdn.com/ARCEUS/Pokemon/Gible.png", "https://rerollcdn.com/ARCEUS/Pokemon/Gible_s.png"},
{"444", "188", "Gabite", "ガバイト", "尖牙陸鯊", "dragon", "ground", "140", "56", "https://rerollcdn.com/ARCEUS/Pokemon/Gabite.png", "https://rerollcdn.com/ARCEUS/Pokemon/Gabite_s.png"},
{"445", "189", "Garchomp", "ガブリアス", "烈咬陸鯊", "dragon", "ground", "190", "95", "https://rerollcdn.com/ARCEUS/Pokemon/Garchomp.png", "https://rerollcdn.com/ARCEUS/Pokemon/Garchomp_s.png"},
{"299", "190", "Nosepass", "ノズパス", "朝北鼻", "rock", "None", "100", "97", "https://rerollcdn.com/ARCEUS/Pokemon/Nosepass.png", "https://rerollcdn.com/ARCEUS/Pokemon/Nosepass_s.png"},
{"476", "191", "Probopass", "ダイノーズ", "大朝北鼻", "rock", "steel", "140", "340", "https://rerollcdn.com/ARCEUS/Pokemon/Probopass.png", "https://rerollcdn.com/ARCEUS/Pokemon/Probopass_s.png"},
{"100", "192", "Voltorb", "ビリリダマ", "霹靂電球", "electric", "None", "50", "10.4", "https://rerollcdn.com/ARCEUS/Pokemon/Voltorb%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Voltorb%20Hisuian_s.png"},
{"101", "193", "Electrode", "マルマイン", "頑皮雷彈", "electric", "None", "120", "66.6", "https://rerollcdn.com/ARCEUS/Pokemon/Electrode%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Electrode%20Hisuian_s.png"},
{"479", "194", "Rotom", "ロトム", "洛托姆", "electric", "ghost", "30", "0.3", "https://rerollcdn.com/ARCEUS/Pokemon/Rotom.png", "https://rerollcdn.com/ARCEUS/Pokemon/Rotom_s.png"},
{"433", "195", "Chingling", "リーシャン", "鈴鐺響", "psychic", "None", "20", "0.6", "https://rerollcdn.com/ARCEUS/Pokemon/Chingling.png", "https://rerollcdn.com/ARCEUS/Pokemon/Chingling_s.png"},
{"358", "196", "Chimecho", "チリーン", "風鈴鈴", "psychic", "None", "60", "1", "https://rerollcdn.com/ARCEUS/Pokemon/Chimecho.png", "https://rerollcdn.com/ARCEUS/Pokemon/Chimecho_s.png"},
{"200", "197", "Misdreavus", "ムウマ", "夢妖", "ghost", "None", "70", "1", "https://rerollcdn.com/ARCEUS/Pokemon/Misdreavus.png", "https://rerollcdn.com/ARCEUS/Pokemon/Misdreavus_s.png"},
{"429", "198", "Mismagius", "ムウマージ", "夢妖魔", "ghost", "None", "90", "4.4", "https://rerollcdn.com/ARCEUS/Pokemon/Mismagius.png", "https://rerollcdn.com/ARCEUS/Pokemon/Mismagius_s.png"},
{"173", "199", "Cleffa", "ピィ", "皮寶寶", "fairy", "None", "30", "3", "https://rerollcdn.com/ARCEUS/Pokemon/Cleffa.png", "https://rerollcdn.com/ARCEUS/Pokemon/Cleffa_s.png"},
{"35", "200", "Clefairy", "ピッピ", "皮皮", "fairy", "None", "60", "7.5", "https://rerollcdn.com/ARCEUS/Pokemon/Clefairy.png", "https://rerollcdn.com/ARCEUS/Pokemon/Clefairy_s.png"},
{"36", "201", "Clefable", "ピクシー", "皮可西", "fairy", "None", "130", "40", "https://rerollcdn.com/ARCEUS/Pokemon/Clefable.png", "https://rerollcdn.com/ARCEUS/Pokemon/Clefable_s.png"},
{"215", "202", "Sneasel", "ニューラ", "狃拉", "dark", "ice", "90", "28", "https://rerollcdn.com/ARCEUS/Pokemon/Sneasel%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Sneasel%20Hisuian_s.png"},
{"903", "203", "Sneasler", "オオニューラ", "大狃拉", "fighting", "poison", "130", "43", "https://rerollcdn.com/ARCEUS/Pokemon/Sneasler.png", "https://rerollcdn.com/ARCEUS/Pokemon/Sneasler_s.png"},
{"461", "204", "Weavile", "マニューラ", "瑪狃拉", "dark", "ice", "110", "34", "https://rerollcdn.com/ARCEUS/Pokemon/Weavile.png", "https://rerollcdn.com/ARCEUS/Pokemon/Weavile_s.png"},
{"361", "205", "Snorunt", "ユキワラシ", "雪童子", "ice", "None", "70", "16.8", "https://rerollcdn.com/ARCEUS/Pokemon/Snorunt.png", "https://rerollcdn.com/ARCEUS/Pokemon/Snorunt_s.png"},
{"362", "206", "Glalie", "オニゴーリ", "冰鬼護", "ice", "None", "150", "256.5", "https://rerollcdn.com/ARCEUS/Pokemon/Glalie.png", "https://rerollcdn.com/ARCEUS/Pokemon/Glalie_s.png"},
{"478", "207", "Froslass", "ユキメノコ", "雪妖女", "ice", "ghost", "130", "26.6", "https://rerollcdn.com/ARCEUS/Pokemon/Froslass.png", "https://rerollcdn.com/ARCEUS/Pokemon/Froslass_s.png"},
{"408", "208", "Cranidos", "ズガイドス", "頭蓋龍", "rock", "None", "90", "31.5", "https://rerollcdn.com/ARCEUS/Pokemon/Cranidos.png", "https://rerollcdn.com/ARCEUS/Pokemon/Cranidos_s.png"},
{"409", "209", "Rampardos", "ラムパルド", "戰槌龍", "rock", "None", "160", "102.5", "https://rerollcdn.com/ARCEUS/Pokemon/Rampardos.png", "https://rerollcdn.com/ARCEUS/Pokemon/Rampardos_s.png"},
{"410", "210", "Shieldon", "タテトプス", "盾甲龍", "rock", "steel", "50", "57", "https://rerollcdn.com/ARCEUS/Pokemon/Shieldon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Shieldon_s.png"},
{"411", "211", "Bastiodon", "トリデプス", "護城龍", "rock", "steel", "130", "149.5", "https://rerollcdn.com/ARCEUS/Pokemon/Bastiodon.png", "https://rerollcdn.com/ARCEUS/Pokemon/Bastiodon_s.png"},
{"220", "212", "Swinub", "ウリムー", "小山豬", "ice", "ground", "40", "6.5", "https://rerollcdn.com/ARCEUS/Pokemon/Swinub.png", "https://rerollcdn.com/ARCEUS/Pokemon/Swinub_s.png"},
{"221", "213", "Piloswine", "イノムー", "長毛豬", "ice", "ground", "110", "55.8", "https://rerollcdn.com/ARCEUS/Pokemon/Piloswine.png", "https://rerollcdn.com/ARCEUS/Pokemon/Piloswine_s.png"},
{"473", "214", "Mamoswine", "マンムー", "象牙豬", "ice", "ground", "250", "291", "https://rerollcdn.com/ARCEUS/Pokemon/Mamoswine.png", "https://rerollcdn.com/ARCEUS/Pokemon/Mamoswine_s.png"},
{"712", "215", "Bergmite", "カチコール", "冰寶", "ice", "None", "100", "99.5", "https://rerollcdn.com/ARCEUS/Pokemon/Bergmite.png", "https://rerollcdn.com/ARCEUS/Pokemon/Bergmite_s.png"},
{"713", "216", "Avalugg", "クレベース", "冰岩怪", "ice", "None", "200", "505", "https://rerollcdn.com/ARCEUS/Pokemon/Avalugg%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Avalugg%20Hisuian_s.png"},
{"459", "217", "Snover", "ユキカブリ", "雪笠怪", "grass", "ice", "100", "50.5", "https://rerollcdn.com/ARCEUS/Pokemon/Snover.png", "https://rerollcdn.com/ARCEUS/Pokemon/Snover_s.png"},
{"460", "218", "Abomasnow", "ユキノオー", "暴雪王", "grass", "ice", "220", "135.5", "https://rerollcdn.com/ARCEUS/Pokemon/Abomasnow.png", "https://rerollcdn.com/ARCEUS/Pokemon/Abomasnow_s.png"},
{"570", "219", "Zorua", "ゾロア", "索羅亞", "dark", "None", "70", "12.5", "https://rerollcdn.com/ARCEUS/Pokemon/Zorua%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Zorua%20Hisuian_s.png"},
{"571", "220", "Zoroark", "ゾロアーク", "索羅亞克", "dark", "None", "160", "81.1", "https://rerollcdn.com/ARCEUS/Pokemon/Zoroark%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Zoroark%20Hisuian_s.png"},
{"627", "221", "Rufflet", "ワシボン", "毛頭小鷹", "normal", "flying", "50", "10.5", "https://rerollcdn.com/ARCEUS/Pokemon/Rufflet.png", "https://rerollcdn.com/ARCEUS/Pokemon/Rufflet_s.png"},
{"628", "222", "Braviary", "ウォーグル", "勇士雄鷹", "normal", "flying", "150", "41", "https://rerollcdn.com/ARCEUS/Pokemon/Braviary%20Hisuian.png", "https://rerollcdn.com/ARCEUS/Pokemon/Braviary%20Hisuian_s.png"},
{"447", "223", "Riolu", "リオル", "利歐路", "fighting", "None", "70", "20.2", "https://rerollcdn.com/ARCEUS/Pokemon/Riolu.png", "https://rerollcdn.com/ARCEUS/Pokemon/Riolu_s.png"},
{"448", "224", "Lucario", "ルカリオ", "路卡利歐", "fighting", "steel", "120", "54", "https://rerollcdn.com/ARCEUS/Pokemon/Lucario.png", "https://rerollcdn.com/ARCEUS/Pokemon/Lucario_s.png"},
{"480", "225", "Uxie", "ユクシー", "由克希", "psychic", "None", "30", "0.3", "https://rerollcdn.com/ARCEUS/Pokemon/Uxie.png", "https://rerollcdn.com/ARCEUS/Pokemon/Uxie_s.png"},
{"481", "226", "Mesprit", "エムリット", "艾姆利多", "psychic", "None", "30", "0.3", "https://rerollcdn.com/ARCEUS/Pokemon/Mesprit.png", "https://rerollcdn.com/ARCEUS/Pokemon/Mesprit_s.png"},
{"482", "227", "Azelf", "アグノム", "亞克諾姆", "psychic", "None", "30", "0.3", "https://rerollcdn.com/ARCEUS/Pokemon/Azelf.png", "https://rerollcdn.com/ARCEUS/Pokemon/Azelf_s.png"},
{"485", "228", "Heatran", "ヒードラン", "席多藍恩", "fire", "steel", "170", "430", "https://rerollcdn.com/ARCEUS/Pokemon/Heatran.png", "https://rerollcdn.com/ARCEUS/Pokemon/Heatran_s.png"},
{"486", "229", "Regigigas", "レジギガス", "雷吉奇卡斯", "normal", "None", "370", "420", "https://rerollcdn.com/ARCEUS/Pokemon/Regigigas.png", "https://rerollcdn.com/ARCEUS/Pokemon/Regigigas_s.png"},
{"488", "230", "Cresselia", "クレセリア", "克雷色利亞", "psychic", "None", "150", "85.6", "https://rerollcdn.com/ARCEUS/Pokemon/Cresselia.png", "https://rerollcdn.com/ARCEUS/Pokemon/Cresselia_s.png"},
{"641", "231", "Tornadus-incarnate", "トルネロス", "龍捲雲", "flying", "None", "150", "63", "https://rerollcdn.com/ARCEUS/Pokemon/Tornadus.png", "https://rerollcdn.com/ARCEUS/Pokemon/Tornadus_s.png"},
{"642", "232", "Thundurus-incarnate", "ボルトロス", "雷電雲", "electric", "flying", "150", "61", "https://rerollcdn.com/ARCEUS/Pokemon/Thundurus.png", "https://rerollcdn.com/ARCEUS/Pokemon/Thundurus_s.png"},
{"645", "233", "Landorus-incarnate", "ランドロス", "土地雲", "ground", "flying", "150", "68", "https://rerollcdn.com/ARCEUS/Pokemon/Landorus.png", "https://rerollcdn.com/ARCEUS/Pokemon/Landorus_s.png"},
{"905", "234", "Enamorus", "ラブトロス", "眷戀魚", "fairy", "flying", "160", "48", "https://rerollcdn.com/ARCEUS/Pokemon/Enamorus.png", "https://rerollcdn.com/ARCEUS/Pokemon/Enamorus_s.png"},
{"483", "235", "Dialga", "ディアルガ", "帝牙盧卡", "steel", "dragon", "540", "683", "https://rerollcdn.com/ARCEUS/Pokemon/Dialga.png", "https://rerollcdn.com/ARCEUS/Pokemon/Dialga_s.png"},
{"484", "236", "Palkia", "パルキア", "帕路奇亞", "water", "dragon", "420", "336", "https://rerollcdn.com/ARCEUS/Pokemon/Palkia.png", "https://rerollcdn.com/ARCEUS/Pokemon/Palkia_s.png"},
{"487", "237", "Giratina-altered", "ギラティナ", "騎拉帝納", "ghost", "dragon", "450", "750", "https://rerollcdn.com/ARCEUS/Pokemon/Giratina.png", "https://rerollcdn.com/ARCEUS/Pokemon/Giratina_s.png"},
{"493", "238", "Arceus", "アルセウス", "阿爾宙斯", "normal", "None", "320", "320", "https://rerollcdn.com/ARCEUS/Pokemon/Arceus.png", "https://rerollcdn.com/ARCEUS/Pokemon/Arceus_s.png"},
{"489", "239", "Phione", "フィオネ", "霏歐納", "water", "None", "40", "3.1", "https://rerollcdn.com/ARCEUS/Pokemon/Phione.png", "https://rerollcdn.com/ARCEUS/Pokemon/Phione_s.png"},
{"490", "240", "Manaphy", "マナフィ", "瑪納霏", "water", "None", "30", "1.4", "https://rerollcdn.com/ARCEUS/Pokemon/Manaphy.png", "https://rerollcdn.com/ARCEUS/Pokemon/Manaphy_s.png"},
{"492", "241", "Shaymin-land", "シェイミ", "謝米", "grass", "None", "20", "2.1", "https://rerollcdn.com/ARCEUS/Pokemon/Shaymin.png", "https://rerollcdn.com/ARCEUS/Pokemon/Shaymin_s.png"},
{"491", "242", "Darkrai", "ダークライ", "達克萊伊", "dark", "None", "150", "50.5", "https://rerollcdn.com/ARCEUS/Pokemon/Darkrai.png", "https://rerollcdn.com/ARCEUS/Pokemon/Darkrai_s.png"}
        };
        return allpokemon;
    }

    public static String[] pokemonname(){
        String[] name = {"木木梟", "投羽梟", "狙射樹梟", "火球鼠", "火岩鼠", "火爆獸", "水水獺", "雙刃丸", "大劍鬼", "大牙狸", "大尾狸", "姆克兒", "姆克鳥",
                "姆克鷹", "小貓怪", "勒克貓", "倫琴貓", "刺尾蟲", "甲殼繭", "狩獵鳳蝶", "盾甲繭", "毒粉蛾", "小火馬", "烈焰馬", "伊布", "水伊布", "雷伊布", "火伊布", "太陽伊布",
                "月亮伊布", "葉伊布", "冰伊布", "仙子伊布", "超音蝠", "大嘴蝠", "超音蝠", "飄飄球", "隨風球", "圓法師", "音箱蟀", "泳圈鼬", "浮潛鼬", "結草兒", "結草貴婦", "紳士蛾",
                "小拳石", "隆隆石", "隆隆岩", "驚角鹿", "詭角鹿", "小卡比獸", "卡比獸", "派拉斯", "派拉斯特", "皮丘", "皮卡丘", "雷丘", "凱西", "勇基拉", "胡地", "小火焰猴", "猛火猴",
                "烈焰猴", "捲捲耳", "長耳兔", "櫻花寶", "櫻花兒", "可達鴨", "哥達鴨", "三蜜蜂", "蜂女王", "飛天螳螂", "巨鉗螳螂", "劈斧螳螂", "赫拉克羅斯", "魔尼尼", "魔牆人偶",
                "長尾怪手", "雙尾怪手", "鯉魚王", "暴鯉龍", "無殼海兔", "海兔獸", "千針魚", "萬針魚", "小福蛋", "吉利蛋", "幸福蛋", "含羞苞", "毒薔薇", "羅絲雷朵", "尖牙籠",
                "百合根娃娃", "裙兒小姐", "蔓藤怪", "巨蔓藤", "泥泥鰍", "鯰魚王", "不良蛙", "毒骷蛙", "拉魯拉絲", "奇魯莉安", "沙奈朵", "艾路雷朵", "蜻蜻蜓", "遠古巨蜓", "沙河馬",
                "河馬獸", "帕奇利茲", "臭鼬噗", "坦克臭鼬", "熊寶寶", "圈圈熊", "月月熊", "黏黏寶", "黏美兒", "黏美龍", "大岩蛇", "大鋼蛇", "獨角犀牛", "鑽角犀獸", "超甲狂犀", "盆才怪",
                "樹才怪", "大舌頭", "大舌舔", "波克比", "波克基古", "波克基斯", "草苗龜", "樹林龜", "土台龜", "多邊獸", "多邊獸Ⅱ", "多邊獸Ｚ", "鬼斯", "鬼斯通", "耿鬼", "花岩怪",
                "黑暗鴉", "烏鴉頭頭", "未知圖騰", "海豹球", "海魔獅", "帝牙海獅", "鐵炮魚", "章魚桶", "鉗尾蠍", "龍王蠍", "卡蒂狗", "風速狗", "魅力喵", "東施喵", "腕力", "豪力", "怪力",
                "聒噪鳥", "夜巡靈", "彷徨夜靈", "黑夜魔靈", "波加曼", "波皇子", "帝王拿波", "小球飛魚", "巨翅飛魚", "野蠻鱸魚", "幽尾玄魚", "六尾", "九尾", "瑪瑙水母", "毒刺水母", "螢光魚",
                "霓虹魚", "鴨嘴寶寶", "鴨嘴火獸", "鴨嘴炎獸", "小磁怪", "三合一磁怪", "自爆磁怪", "銅鏡怪", "青銅鐘", "電擊怪", "電擊獸", "電擊魔獸", "天蠍", "天蠍王", "圓陸鯊", "尖牙陸鯊",
                "烈咬陸鯊", "朝北鼻", "大朝北鼻", "霹靂電球", "頑皮雷彈", "洛托姆", "鈴鐺響", "風鈴鈴", "夢妖", "夢妖魔", "皮寶寶", "皮皮", "皮可西", "狃拉", "大狃拉", "瑪狃拉", "雪童子", "冰鬼護",
                "雪妖女", "頭蓋龍", "戰槌龍", "盾甲龍", "護城龍", "小山豬", "長毛豬", "象牙豬", "冰寶", "冰岩怪", "雪笠怪", "暴雪王", "索羅亞", "索羅亞克", "毛頭小鷹", "勇士雄鷹", "利歐路", "路卡利歐",
                "由克希", "艾姆利多", "亞克諾姆", "席多藍恩", "雷吉奇卡斯", "克雷色利亞", "龍捲雲", "雷電雲", "土地雲", "眷戀雲", "帝牙盧卡", "帕路奇亞", "騎拉帝納", "阿爾宙斯", "霏歐納", "瑪納霏", "謝米", "達克萊伊"
        };
        return name;
    }
}
